// Double-tap regression: every hand-flow button does its job exactly once, however fast it is hit.
const { chromium } = require('playwright');
const passGate = require('/Users/rick/Downloads/bluff/gate');
const log=[];let bad=0;const ok=(n,c,note)=>{log.push(`${c?'ok ':'BAD'} ${n}${note?' — '+note:''}`);if(!c)bad++;};
(async()=>{
  const b=await chromium.launch();
  const p=await b.newPage({viewport:{width:390,height:844}});
  await p.addInitScript(()=>{window.__talkAlways=true;window.__ticks=0;const oI=window.setInterval;window.setInterval=function(f,ms,...a){if(f&&f.name==='botTick')window.__ticks++;return oI(f,ms,...a)};});
  const errs=[];p.on('pageerror',e=>errs.push(e.message.slice(0,120)+' '+String(e.stack||'').split('\n').slice(1,2).join('').trim().replace(/.*index.html:/,'L')));
  await p.goto('file:///Users/rick/Downloads/bluff/index.html'); await passGate(p);
  await p.fill('#hnd','D'+Math.random().toString(36).replace(/[^a-z0-9]/g,'').slice(0,5).toUpperCase());
  await p.click('#go2'); await p.waitForSelector('#cash');
  await p.evaluate(()=>{window.__pa=0;window.__pp=0;const a=phaseAction;phaseAction=function(){window.__pa++;return a.apply(this,arguments)};const q=phasePlay;phasePlay=function(){window.__pp++;return q.apply(this,arguments)};});
  await p.evaluate(()=>startMatch('cash')); await p.waitForSelector('.wcard');
  // setter: hammer every button
  await p.locator('.wcard').nth(1).click();
  await p.evaluate(()=>{const b=document.getElementById('pickBtn');b.click();b.click();b.click();});
  await p.waitForSelector('.tell'); ok('CHOOSE A TELL ×3 → one tell screen', (await p.locator('#tellBtn').count())===1);
  await p.locator('.tell').nth(0).click();
  await p.evaluate(()=>{const b=document.getElementById('tellBtn');b.click();b.click();});
  await p.waitForSelector('#stk > *'); await p.locator('#stk > *').nth(0).click();
  await p.evaluate(()=>{const b=document.getElementById('goBtn');b.click();b.click();b.click();});
  await p.waitForTimeout(300);
  ok('DEAL IT ×3 → phaseAction once', (await p.evaluate(()=>window.__pa))===1, String(await p.evaluate(()=>window.__pa)));
  const waitNx=async()=>{const t=Date.now();while(Date.now()-t<120000){if(await p.evaluate(()=>{const b=document.getElementById('nx');return !!(b&&b.offsetParent!==null)}))return true;await p.waitForTimeout(250);}return false;};
  ok('hand 1 finished', await waitNx());
  const h0=await p.evaluate(()=>S.hand);
  await p.evaluate(()=>{const b=document.getElementById('nx');b.click();b.click();b.click();});
  await p.waitForTimeout(600);
  ok('NEXT HAND ×3 → one hand advanced', (await p.evaluate(()=>S.hand))===h0+1, `${h0} → ${await p.evaluate(()=>S.hand)}`);
  const waitCall=async()=>{const t=Date.now();while(Date.now()-t<60000){if(await p.evaluate(()=>!!(document.getElementById('callB')&&document.getElementById('callB').offsetParent&&S.phase==='action')))return true;await p.waitForTimeout(150);}return false;};
  ok('hand 2: fold/call offered', await waitCall());
  const before=await p.evaluate(()=>({chips:S.seats[0].chips,pot:S.pot,oi:S.oi,stake:S.stake}));
  await p.evaluate(()=>{const b=document.getElementById('callB');b.click();b.click();b.click();document.getElementById('foldB').click();});
  await p.waitForTimeout(200);
  const after=await p.evaluate(()=>({chips:S.seats[0].chips,pot:S.pot,oi:S.oi,state:S.seats[0].state,dis:document.getElementById('callB')?document.getElementById('callB').disabled:null}));
  ok('CALL ×3 + FOLD → charged once', after.chips===before.chips-before.stake&&after.pot===before.pot+before.stake, `chips ${before.chips}→${after.chips}, pot ${before.pot}→${after.pot}`);
  ok('…one seat advanced', after.oi===before.oi+1, `${before.oi}→${after.oi}`);
  ok('…state is call, not fold', after.state==='call', after.state);
  ok('…buttons disabled after acting', after.dis===true);
  const t=Date.now();while(Date.now()-t<30000){if((await p.evaluate(()=>S.phase))==='play')break;await p.waitForTimeout(150);}
  await p.waitForTimeout(400);
  ok('phasePlay ran once for this hand', (await p.evaluate(()=>window.__pp))===2, String(await p.evaluate(()=>window.__pp)));
  ok('one botTick clock per play phase', (await p.evaluate(()=>window.__ticks))===2, String(await p.evaluate(()=>window.__ticks)));
  const key=k=>p.locator(`.key[data-k="${k}"]`).dispatchEvent('pointerdown');
  const w=await p.evaluate(()=>S.word);for(const ch of w)await key(ch);await key('↵');
  ok('hand 2 finished', await waitNx()); await p.click('#nx');
  ok('hand 3: fold/call offered', await waitCall());
  const c3=await p.evaluate(()=>S.seats[0].chips);
  await p.evaluate(()=>{document.getElementById('foldB').click();document.getElementById('callB').click();});
  await p.waitForTimeout(200);
  const a3=await p.evaluate(()=>({chips:S.seats[0].chips,state:S.seats[0].state}));
  ok('FOLD then CALL → folded, nothing charged', a3.state==='fold'&&a3.chips===c3, `${a3.state} ${c3}→${a3.chips}`);
  ok('hand 3 finished', await waitNx());
  ok('no page errors across three hands', errs.length===0, errs.join(' | '));
  console.log(log.join('\n'));
  console.log(`\nDOUBLE-TAP ${bad?'FAIL':'PASS'} · ${log.length} checks · ${bad} bad · page errors ${errs.length}`);
  await b.close();process.exit(bad?1:0);
})().catch(e=>{console.log(log.join('\n'));console.log('DOUBLE-TAP CRASH',e.message.slice(0,300));process.exit(2)});
