"""Lift the deterministic core out of the game and into the server.

The server can only pay people if it computes the same score the game did, and
the only way to guarantee that is for both to run the same code. So the shared
half of the engine is *extracted* from index.html rather than reimplemented:
same PRNG, same decks, same clue menu, same bots, same arithmetic.

Anything that touches the DOM, the audio, the profile or the network is not
here, and must not be. If this script cannot find a symbol it is because
somebody moved it, and the right fix is to fix the name — not to paste a copy.
"""
import os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = open(os.path.join(ROOT, "index.html")).read()

HEADER = '''/* ══════════ THE ENGINE ══════════
   The deterministic core of BLUFF, lifted verbatim out of the game so the two
   can never drift: same PRNG, same decks, same marking, same clue generation,
   same bot arithmetic. The server needs this because a score it cannot compute
   is a score it cannot pay.

   Everything here is pure. Given a day key and a player's decisions it produces
   exactly one score, and verify.js proves that score is the one the real client
   produced for the same inputs, on real matches, in a real browser.

   GENERATED by tools/build_engine.py from index.html — do not edit by hand.
   Edit the game, then re-run the generator. */

'''


def grab(pattern, what, flags=0):
    m = re.search(pattern, src, flags | re.S)
    if not m:
        print(f"  ! could not find {what}")
        sys.exit(1)
    return m.group(0)


def fn(name):
    """Extract a top-level function by brace matching."""
    i = src.index(f"\nfunction {name}(")
    j = src.index("{", i)
    depth, k = 0, j
    while True:
        if src[k] == "{":
            depth += 1
        elif src[k] == "}":
            depth -= 1
            if depth == 0:
                break
        k += 1
    return src[i + 1:k + 1]


def const(name):
    i = src.index(f"\nconst {name}=")
    j = src.index(";", i)
    # a template literal or an object may contain semicolons; walk properly
    k, depth, tick = i, 0, False
    while k < len(src):
        c = src[k]
        if c == "`":
            tick = not tick
        elif not tick:
            if c in "{[(":
                depth += 1
            elif c in "}])":
                depth -= 1
            elif c == ";" and depth == 0 and k > i:
                break
        k += 1
    return src[i + 1:k + 1]


parts = [HEADER]

# ── the data ──
parts.append(const("RAW"))
for g in ("G4", "G5", "G6"):
    parts.append(const(g))
parts.append(const("BAN"))

# ── the shared core, in dependency order ──
parts.append("""
/* the seeded stream: every daily in the world is this function and a date */
let rnd = Math.random;
function setSeed(s){ rnd = (s == null) ? Math.random : mulberry32(s); }
function withRng(g, fn){ const s = rnd; rnd = g; try { return fn(); } finally { rnd = s; } }
let S_SEATED = null;
""")
for name in ("mulberry32", "hashStr"):
    parts.append(fn(name))

parts.append(const("LENS"))
parts.append("""const DECKS={},RATE={},WORD={};
LENS.forEach(L=>DECKS[L]=[]);
RAW.split("\\n").forEach(line=>{
  const [w,rate,pron,def]=line.split("|");
  if(!w||!DECKS[w.length])return;
  DECKS[w.length].push(w);RATE[w]=+rate;WORD[w]={p:pron,d:def};
});""")
parts.append(const("AL"))
parts.append(const("VOW"))
parts.append("""const COMMON={};
LENS.forEach(L=>{
  COMMON[L]=AL.map(c=>[c,DECKS[L].filter(w=>w.includes(c)).length])
    .sort((a,b)=>b[1]-a[1]).slice(0,12).map(x=>x[0]);
});""")
parts.append(const("TELLCAP_F"))
parts.append(const("TELLCAP"))
parts.append(fn("capFor"))
parts.append("""const BANDS={};
LENS.forEach(L=>{
  const s=DECKS[L].map(w=>RATE[w]).sort((a,b)=>a-b);
  BANDS[L]=[.2,.4,.6,.8].map(q=>s[Math.floor(q*(s.length-1))]);
});""")
parts.append(const("GDICT"))
parts.append(fn("isWord"))
parts.append(const("LEET"))
parts.append(fn("foldText"))
parts.append(fn("cleanText"))

for name in ("evaluate", "survivors", "shuf", "offerTells",
             "solveOnce", "crackOdds", "botParams", "dealLength", "dealCards",
             "buildScript"):
    parts.append(fn(name))
parts.append(const("OPEN"))
parts.append(const("PINBIAS"))
parts.append(const("LEGIB"))
parts.append(const("ANTE"))
parts.append(const("GUESSES"))
parts.append(const("BUYIN"))
parts.append(const("ROSTER"))
parts.append(const("blankRivals"))

# ── the server-only half, kept by hand ──
parts.append(open(os.path.join(ROOT, "server", "src", "daily.js")).read())

parts.append("""
module.exports = {
  DECKS, RATE, WORD, LENS, AL, VOW, COMMON, OPEN, PINBIAS, LEGIB,
  ANTE, STAKES, HANDS, SEATS, GUESSES, BET, BUYIN, TELLCAP, BANDS, GDICT, BAN,
  mulberry32, hashStr, setSeed, withRng, evaluate, consistent, survivors,
  capFor, shuf, offerTells, isWord, cleanText, foldText,
  solveOnce, crackOdds, botParams, dealLength, dealCards, buildScript,
  blankRivals, setupDay, botCalls, botPlays, handScore, runDaily
};
""")

out = "\n".join(p.rstrip() + "\n" for p in parts)
path = os.path.join(ROOT, "server", "src", "engine.js")
open(path, "w").write(out)
print(f"engine.js: {len(out)/1024:.0f} KB, {out.count(chr(10))} lines")
